yumroad/blueprints/product.py
from flask import Blueprint, render_template, abort

from yumroad.models import Product

product = Blueprint('products', __name__)

@product.route('/')
def index():
    # all_products = Product.query.all()
    # return all_products
    product_all = Product.query.all()
    return render_template('/products/index.html', product=product_all)

@product.route('/<int:product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('/products/details.html', product=product)

@product.errorhandler(404)
def not_found(exception):
    return render_template('products/404.html'), 404

yumroad/blueprints/products.py
from flask import Blueprint, render_template, abort, redirect, url_for, request, session
from flask_login.utils import login_required
from werkzeug.wrappers import response

from yumroad.extensions import db
from yumroad.models import Product
from yumroad.forms import ProductForm

bp_products = Blueprint('products', __name__)

@bp_products.route('/')
def index():

    # print(session)
    # all_products = Product.query.all()
    # return all_products
    product_all = Product.query.all()
    return render_template('/products/index.html', product=product_all)

@bp_products.route('/<int:product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('/products/details.html', product=product)

@bp_products.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProductForm()
    if form.validate_on_submit(): #/Validate = Post
        product = Product(name=form.name.data, description=form.description.data)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('products.details', product_id=product.id))
    return render_template('/products/create.html', form=form)

@bp_products.route('/<int:product_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(product_id): 
    product = Product.query.get_or_404(product_id)
    form = ProductForm(obj=product)

    if form.validate_on_submit(): #Kiem tra hop le submit //Post
        product.name = form.name.data
        product.description = form.description.data
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('products.details', product_id=product.id))
    return render_template('/products/edit.html', product = product, form=form)

@bp_products.errorhandler(404)
def not_found(exception):
    return render_template('products/404.html'), 404

yumroad/templates/products/create.html
{% extends 'base_layout.html' %}
{% from '_formhelpers.html' import render_field %}
{% block title %}Yumroad | Create New Product{% endblock title %}

{% block content %}
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.name) }}
        {{ render_field(form.description) }}
        <button type="submit" class="btn btn-success">Create Product</button>
    </form>
{% endblock content %}

yumroad/templates/products/details.html
{% extends 'base_layout.html' %}

{% block title %}{{ product.name }}{% endblock title %}

{% block content %}
<h1>{{ product.name }}</h1>
        
<hr>
<span>{{product.description}}</span>
<hr>
<button class="btn btn-success">Purchase coming soon</button>
<a href="{{ url_for('products.edit', product_id=product.id) }}" class="btn btn-success">Edit</a>
{% endblock content %}

yumroad/templates/products/edit.html
{% extends 'base_layout.html' %}
{% from '_formhelpers.html' import render_field %}
{% block title %}Yumroad | Edit{{ product.name }}{% endblock title %}

{% block content %}
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.name) }}
        {{ render_field(form.description) }}
        <button type="submit" class="btn btn-success">Finish Product</button>
    </form>
{% endblock content %}

yumroad/templates/products/index.html
{% extends 'base_layout.html' %}

{% block title %}All Products{% endblock title %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
        {% for product in product %}
            <tr>
                <td>
                    <a href="{{ url_for('products.details', product_id=product.id) }}">{{ product.name }}</a>
                </td>
                <td>{{ product.description }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <hr>
    <button class="btn btn-success">Home</button>
{% endblock content %} 