yumroad/blueprints/products.py
from flask import Blueprint, render_template, abort, redirect, url_for, request, session
from flask_login.utils import login_required
from werkzeug.wrappers import response

from yumroad.extensions import db
from yumroad.models import Product
from yumroad.forms import ProductForm

bp_products = Blueprint('products', __name__)

@bp_products.route('/')
def index():

    # print(session)
    # all_products = Product.query.all()
    # return all_products
    product_all = Product.query.all()
    return render_template('/products/index.html', product=product_all)

@bp_products.route('/<int:product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('/products/details.html', product=product)

@bp_products.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProductForm()
    if form.validate_on_submit(): #/Validate = Post
        product = Product(name=form.name.data, description=form.description.data)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('products.details', product_id=product.id))
    return render_template('/products/create.html', form=form)

@bp_products.route('/<int:product_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(product_id): 
    product = Product.query.get_or_404(product_id)
    form = ProductForm(obj=product)

    if form.validate_on_submit(): #Kiem tra hop le submit //Post
        product.name = form.name.data
        product.description = form.description.data
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('products.details', product_id=product.id))
    return render_template('/products/edit.html', product = product, form=form)

@bp_products.errorhandler(404)
def not_found(exception):
    return render_template('products/404.html'), 404

yumroad/blueprints/users.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from flask_login import current_user
from flask_login.utils import login_user, logout_user

from yumroad.extensions import db, login_manager
from yumroad.models import User
from yumroad.forms import LoginForm, SignupForm

bp_user = Blueprint('user', __name__)
#user loader take in a User ID and return out
#User object
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    flash('__You need to login', 'warning')
    session['after_login'] = request.url #Flash into url => session co flash, du cho flash nam tren hay nam duoi session['after]
    print(session)
    return redirect( url_for('user.login') )

@bp_user.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash("__flash__You are already logged in", "warning")
        return redirect(url_for('products.index'))
    form = SignupForm()
    if form.validate_on_submit():
        #create a user
        user = User.create(form.email.data, form.password.data)
        db.session.add(user)
        db.session.commit()
        #Dang nhap san
        login_user(user)
        flash('__flash__Registered successfully', 'success')
        #we need to tell flask_login How to know that a Cookie belongs to a specific user (User cu the) 
        return redirect(url_for('products.index'))
    return render_template('/users/register.html', form=form)

@bp_user.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    #if current User is login
    if current_user.is_authenticated:
        flash("__flash__You are already logged in", "warning")
        return redirect(url_for('products.index'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one() #one = gap la dung tim
        if user:
            login_user(user=user)
        flash('__flash__Logged in successfully', 'success')
        #we need to tell flask_login How to know that a Cookie belongs to a specific user (User cu the)
        #Neu login xong thi quay lai vi tri url truoc hoac ve index
        return redirect(session.get('after_login') or url_for('products.index'))
    return render_template('/users/login.html', form=form)

@bp_user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('products.index'))

yumroad/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group">
        <label for="{{ field.name }}">{{ field.label }}</label>
        <!-- {{ field(class_="form-control is-invalid") }} -->
        {{ field(class_=' '.join(['form-control', 'is-invalid' if field.errors else '']), **kwargs) | safe }}
        <ul class="invalid-feedback errors">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

yumroad/templates/_macros.html
{% macro render_flashes() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="container mt-4">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{% endmacro %}

yumroad/templates/base_layout.html
{% from '_macros.html' import render_flashes %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between yumroad-main-color">
        <div class="brand">Yumroad</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarContent">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('products.index') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('products.create') }}">Create Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="navbar-item">
                    {% if current_user.is_authenticated %}
                        <a class="ml-3"> {{ current_user.email }}</a>
                        <a href="{{ url_for('user.logout') }}" class="nav-link">Sign Out</a>
                    {% else %}
                        <a href="{{ url_for('user.register') }}" class="nav-link">Register</a>
                        <a href="{{ url_for('user.login') }}" class="nav-link">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    {{ render_flashes() }}
    <div class="container mt-5">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>